### ISSUE TITLE
No longer available?

### ISSUE THREAD

**Issue by jonimatix** [DanielArthurUK/medium-downloader#5]
Hi,

The link on Chrome Web Store seems unavailable? 

Can you kindly advise?

Thanks

**Comment by farrukhahmed4220** [comment]
The link is no longer available on Chrome Web Store. Author, Kindly update about this issue.

Thanks.

**Comment by danarth** [comment]
Hi both, this was a pet project I started a few years ago and I haven't had the time to keep updating it. As a result, a lot of people negatively reviewed the extension on the Chrome store and it was removed. I'll archive this repository now, but feel free to fork it and try and get it working again!

Thanks!
